import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Searchbox from '../src/Searchbox'
import { trending, search } from '../src/api'
import Card from '../src/Card'
import Masonry from "react-masonry-css"
import Navbar from '../src/Navbar'
interface Props {
  gifs: any;
}

const Home: NextPage<Props> = ({ gifs }) => {
  console.log(gifs)

  const breakpoints = {
    default: 4,
    900: 3,
    700: 2,
    500: 1,
  }
  
  return (
      <div className="container text-center justify-center">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='justify-center align-center '>
          <Navbar />
          <h1 className='text-3xl font-bold text-slate-400 my-10'>ADVANCED JS STUDY GROUP</h1>
          <Searchbox />
          <div className=''>
            <h4 className='text-xl text-left pl-2 mb-4 font-bold text-slate-400'>📈 Trending</h4>
            <Masonry
              breakpointCols={breakpoints}
              className="my-masonry-grid"
              columnClassName="my-masonry-grid_column"
            >
              {gifs.map((item:any)=> <div key={item.id}><Card gif={item} /></div>)}
            </Masonry>
          </div>
        </main>
      </div>
    )
}

export const getStaticProps: GetStaticProps = async () => {
  const gifs = await trending();

  return {
    props: {
      gifs,
    },
    revalidate: 3600*24,
  };
};

export default Home